/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrafegoPagoRouteImport } from './routes/trafego-pago'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SolicitarOrcamentoRouteImport } from './routes/solicitar-orcamento'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapServicesDotxmlRouteImport } from './routes/sitemap-services[.]xml'
import { Route as SitemapPagesDotxmlRouteImport } from './routes/sitemap-pages[.]xml'
import { Route as SitemapMarketplaceDotxmlRouteImport } from './routes/sitemap-marketplace[.]xml'
import { Route as SitemapEditorialDotxmlRouteImport } from './routes/sitemap-editorial[.]xml'
import { Route as SitemapCityServicesDotxmlRouteImport } from './routes/sitemap-city-services[.]xml'
import { Route as SitemapCitiesDotxmlRouteImport } from './routes/sitemap-cities[.]xml'
import { Route as SitemapCasesDotxmlRouteImport } from './routes/sitemap-cases[.]xml'
import { Route as SitemapBlogDotxmlRouteImport } from './routes/sitemap-blog[.]xml'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as SeoRouteImport } from './routes/seo'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QaEventsRouteImport } from './routes/qa-events'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PoliticaPrivacidadeRouteImport } from './routes/politica-privacidade'
import { Route as ParceirosRouteImport } from './routes/parceiros'
import { Route as PainelCrmRouteImport } from './routes/painel-crm'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as IaRouteImport } from './routes/ia'
import { Route as GoogleMeuNegocioRouteImport } from './routes/google-meu-negocio'
import { Route as EstadosRouteImport } from './routes/estados'
import { Route as DesenvolvimentoRouteImport } from './routes/desenvolvimento'
import { Route as CriacaoSitesRouteImport } from './routes/criacao-sites'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ConsultoriaRouteImport } from './routes/consultoria'
import { Route as CidadesRouteImport } from './routes/cidades'
import { Route as AutomacaoRouteImport } from './routes/automacao'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ServiceRouteImport } from './routes/$service'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as ProfissionalSlugRouteImport } from './routes/profissional.$slug'
import { Route as EstadosStateRouteImport } from './routes/estados.$state'
import { Route as EmpresaSlugRouteImport } from './routes/empresa.$slug'
import { Route as CidadeSlugRouteImport } from './routes/cidade.$slug'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as CasesSlugRouteImport } from './routes/cases.$slug'
import { Route as BlogVendasRouteImport } from './routes/blog.vendas'
import { Route as BlogTrafegoPagoRouteImport } from './routes/blog.trafego-pago'
import { Route as BlogSitesRouteImport } from './routes/blog.sites'
import { Route as BlogSeoRouteImport } from './routes/blog.seo'
import { Route as BlogMarketingLocalRouteImport } from './routes/blog.marketing-local'
import { Route as BlogMapaRouteImport } from './routes/blog.mapa'
import { Route as BlogLandingPagesRouteImport } from './routes/blog.landing-pages'
import { Route as BlogIaRouteImport } from './routes/blog.ia'
import { Route as BlogGoogleMeuNegocioRouteImport } from './routes/blog.google-meu-negocio'
import { Route as BlogConversaoRouteImport } from './routes/blog.conversao'
import { Route as BlogAutomacaoRouteImport } from './routes/blog.automacao'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as CityServiceRouteImport } from './routes/$city.$service'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as BlogClusterClusterRouteImport } from './routes/blog.cluster.$cluster'
import { Route as ApiPublicLeadWebhookRouteImport } from './routes/api/public/lead-webhook'
import { Route as AuthenticatedAppVisitantesRouteImport } from './routes/_authenticated/app.visitantes'
import { Route as AuthenticatedAppSupportRouteImport } from './routes/_authenticated/app.support'
import { Route as AuthenticatedAppReportsRouteImport } from './routes/_authenticated/app.reports'
import { Route as AuthenticatedAppProjectsRouteImport } from './routes/_authenticated/app.projects'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppPortalsRouteImport } from './routes/_authenticated/app.portals'
import { Route as AuthenticatedAppParceiroRouteImport } from './routes/_authenticated/app.parceiro'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/app.notifications'
import { Route as AuthenticatedAppMasterRouteImport } from './routes/_authenticated/app.master'
import { Route as AuthenticatedAppMarketplaceRouteImport } from './routes/_authenticated/app.marketplace'
import { Route as AuthenticatedAppEditorialRouteImport } from './routes/_authenticated/app.editorial'
import { Route as AuthenticatedAppDocumentsRouteImport } from './routes/_authenticated/app.documents'
import { Route as AuthenticatedAppCampaignsRouteImport } from './routes/_authenticated/app.campaigns'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as ApiPublicHooksVisitorsCleanupRouteImport } from './routes/api/public/hooks/visitors-cleanup'
import { Route as ApiPublicHooksSeoMonitorRouteImport } from './routes/api/public/hooks/seo-monitor'
import { Route as ApiPublicHooksLgpdMaintenanceRouteImport } from './routes/api/public/hooks/lgpd-maintenance'
import { Route as ApiPublicHooksIntegrationHealthcheckRouteImport } from './routes/api/public/hooks/integration-healthcheck'
import { Route as ApiPublicHooksAnomalyScanRouteImport } from './routes/api/public/hooks/anomaly-scan'
import { Route as AuthenticatedAppSupportIdRouteImport } from './routes/_authenticated/app.support.$id'
import { Route as AuthenticatedAppProjectsIdRouteImport } from './routes/_authenticated/app.projects.$id'
import { Route as AuthenticatedAppMarketplaceProviderRouteImport } from './routes/_authenticated/app.marketplace.provider'
import { Route as AuthenticatedAppMarketplaceCompanyRouteImport } from './routes/_authenticated/app.marketplace.company'
import { Route as AuthenticatedAppMarketplaceAdminRouteImport } from './routes/_authenticated/app.marketplace.admin'

const TrafegoPagoRoute = TrafegoPagoRouteImport.update({
  id: '/trafego-pago',
  path: '/trafego-pago',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitarOrcamentoRoute = SolicitarOrcamentoRouteImport.update({
  id: '/solicitar-orcamento',
  path: '/solicitar-orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapServicesDotxmlRoute = SitemapServicesDotxmlRouteImport.update({
  id: '/sitemap-services.xml',
  path: '/sitemap-services.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPagesDotxmlRoute = SitemapPagesDotxmlRouteImport.update({
  id: '/sitemap-pages.xml',
  path: '/sitemap-pages.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapMarketplaceDotxmlRoute =
  SitemapMarketplaceDotxmlRouteImport.update({
    id: '/sitemap-marketplace.xml',
    path: '/sitemap-marketplace.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapEditorialDotxmlRoute = SitemapEditorialDotxmlRouteImport.update({
  id: '/sitemap-editorial.xml',
  path: '/sitemap-editorial.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapCityServicesDotxmlRoute =
  SitemapCityServicesDotxmlRouteImport.update({
    id: '/sitemap-city-services.xml',
    path: '/sitemap-city-services.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapCitiesDotxmlRoute = SitemapCitiesDotxmlRouteImport.update({
  id: '/sitemap-cities.xml',
  path: '/sitemap-cities.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapCasesDotxmlRoute = SitemapCasesDotxmlRouteImport.update({
  id: '/sitemap-cases.xml',
  path: '/sitemap-cases.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapBlogDotxmlRoute = SitemapBlogDotxmlRouteImport.update({
  id: '/sitemap-blog.xml',
  path: '/sitemap-blog.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoRoute = SeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QaEventsRoute = QaEventsRouteImport.update({
  id: '/qa-events',
  path: '/qa-events',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaPrivacidadeRoute = PoliticaPrivacidadeRouteImport.update({
  id: '/politica-privacidade',
  path: '/politica-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosRoute = ParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelCrmRoute = PainelCrmRouteImport.update({
  id: '/painel-crm',
  path: '/painel-crm',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleMeuNegocioRoute = GoogleMeuNegocioRouteImport.update({
  id: '/google-meu-negocio',
  path: '/google-meu-negocio',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadosRoute = EstadosRouteImport.update({
  id: '/estados',
  path: '/estados',
  getParentRoute: () => rootRouteImport,
} as any)
const DesenvolvimentoRoute = DesenvolvimentoRouteImport.update({
  id: '/desenvolvimento',
  path: '/desenvolvimento',
  getParentRoute: () => rootRouteImport,
} as any)
const CriacaoSitesRoute = CriacaoSitesRouteImport.update({
  id: '/criacao-sites',
  path: '/criacao-sites',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultoriaRoute = ConsultoriaRouteImport.update({
  id: '/consultoria',
  path: '/consultoria',
  getParentRoute: () => rootRouteImport,
} as any)
const CidadesRoute = CidadesRouteImport.update({
  id: '/cidades',
  path: '/cidades',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacaoRoute = AutomacaoRouteImport.update({
  id: '/automacao',
  path: '/automacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/$service',
  path: '/$service',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionalSlugRoute = ProfissionalSlugRouteImport.update({
  id: '/profissional/$slug',
  path: '/profissional/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadosStateRoute = EstadosStateRouteImport.update({
  id: '/$state',
  path: '/$state',
  getParentRoute: () => EstadosRoute,
} as any)
const EmpresaSlugRoute = EmpresaSlugRouteImport.update({
  id: '/empresa/$slug',
  path: '/empresa/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CidadeSlugRoute = CidadeSlugRouteImport.update({
  id: '/cidade/$slug',
  path: '/cidade/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesSlugRoute = CasesSlugRouteImport.update({
  id: '/cases/$slug',
  path: '/cases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogVendasRoute = BlogVendasRouteImport.update({
  id: '/blog/vendas',
  path: '/blog/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTrafegoPagoRoute = BlogTrafegoPagoRouteImport.update({
  id: '/blog/trafego-pago',
  path: '/blog/trafego-pago',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSitesRoute = BlogSitesRouteImport.update({
  id: '/blog/sites',
  path: '/blog/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSeoRoute = BlogSeoRouteImport.update({
  id: '/blog/seo',
  path: '/blog/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogMarketingLocalRoute = BlogMarketingLocalRouteImport.update({
  id: '/blog/marketing-local',
  path: '/blog/marketing-local',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogMapaRoute = BlogMapaRouteImport.update({
  id: '/blog/mapa',
  path: '/blog/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogLandingPagesRoute = BlogLandingPagesRouteImport.update({
  id: '/blog/landing-pages',
  path: '/blog/landing-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIaRoute = BlogIaRouteImport.update({
  id: '/blog/ia',
  path: '/blog/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogGoogleMeuNegocioRoute = BlogGoogleMeuNegocioRouteImport.update({
  id: '/blog/google-meu-negocio',
  path: '/blog/google-meu-negocio',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogConversaoRoute = BlogConversaoRouteImport.update({
  id: '/blog/conversao',
  path: '/blog/conversao',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAutomacaoRoute = BlogAutomacaoRouteImport.update({
  id: '/blog/automacao',
  path: '/blog/automacao',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CityServiceRoute = CityServiceRouteImport.update({
  id: '/$city/$service',
  path: '/$city/$service',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const BlogClusterClusterRoute = BlogClusterClusterRouteImport.update({
  id: '/blog/cluster/$cluster',
  path: '/blog/cluster/$cluster',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadWebhookRoute = ApiPublicLeadWebhookRouteImport.update({
  id: '/api/public/lead-webhook',
  path: '/api/public/lead-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppVisitantesRoute =
  AuthenticatedAppVisitantesRouteImport.update({
    id: '/visitantes',
    path: '/visitantes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSupportRoute = AuthenticatedAppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppReportsRoute = AuthenticatedAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProjectsRoute =
  AuthenticatedAppProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPortalsRoute = AuthenticatedAppPortalsRouteImport.update({
  id: '/portals',
  path: '/portals',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppParceiroRoute =
  AuthenticatedAppParceiroRouteImport.update({
    id: '/parceiro',
    path: '/parceiro',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMasterRoute = AuthenticatedAppMasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMarketplaceRoute =
  AuthenticatedAppMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEditorialRoute =
  AuthenticatedAppEditorialRouteImport.update({
    id: '/editorial',
    path: '/editorial',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDocumentsRoute =
  AuthenticatedAppDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCampaignsRoute =
  AuthenticatedAppCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicHooksVisitorsCleanupRoute =
  ApiPublicHooksVisitorsCleanupRouteImport.update({
    id: '/api/public/hooks/visitors-cleanup',
    path: '/api/public/hooks/visitors-cleanup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSeoMonitorRoute =
  ApiPublicHooksSeoMonitorRouteImport.update({
    id: '/api/public/hooks/seo-monitor',
    path: '/api/public/hooks/seo-monitor',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLgpdMaintenanceRoute =
  ApiPublicHooksLgpdMaintenanceRouteImport.update({
    id: '/api/public/hooks/lgpd-maintenance',
    path: '/api/public/hooks/lgpd-maintenance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksIntegrationHealthcheckRoute =
  ApiPublicHooksIntegrationHealthcheckRouteImport.update({
    id: '/api/public/hooks/integration-healthcheck',
    path: '/api/public/hooks/integration-healthcheck',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAnomalyScanRoute =
  ApiPublicHooksAnomalyScanRouteImport.update({
    id: '/api/public/hooks/anomaly-scan',
    path: '/api/public/hooks/anomaly-scan',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppSupportIdRoute =
  AuthenticatedAppSupportIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppSupportRoute,
  } as any)
const AuthenticatedAppProjectsIdRoute =
  AuthenticatedAppProjectsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppProjectsRoute,
  } as any)
const AuthenticatedAppMarketplaceProviderRoute =
  AuthenticatedAppMarketplaceProviderRouteImport.update({
    id: '/provider',
    path: '/provider',
    getParentRoute: () => AuthenticatedAppMarketplaceRoute,
  } as any)
const AuthenticatedAppMarketplaceCompanyRoute =
  AuthenticatedAppMarketplaceCompanyRouteImport.update({
    id: '/company',
    path: '/company',
    getParentRoute: () => AuthenticatedAppMarketplaceRoute,
  } as any)
const AuthenticatedAppMarketplaceAdminRoute =
  AuthenticatedAppMarketplaceAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedAppMarketplaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$service': typeof ServiceRoute
  '/auth': typeof AuthRoute
  '/automacao': typeof AutomacaoRoute
  '/cidades': typeof CidadesRoute
  '/consultoria': typeof ConsultoriaRoute
  '/contato': typeof ContatoRoute
  '/criacao-sites': typeof CriacaoSitesRoute
  '/desenvolvimento': typeof DesenvolvimentoRoute
  '/estados': typeof EstadosRouteWithChildren
  '/google-meu-negocio': typeof GoogleMeuNegocioRoute
  '/ia': typeof IaRoute
  '/marketplace': typeof MarketplaceRoute
  '/painel': typeof PainelRoute
  '/painel-crm': typeof PainelCrmRoute
  '/parceiros': typeof ParceirosRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/privacidade': typeof PrivacidadeRoute
  '/qa-events': typeof QaEventsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/seo': typeof SeoRoute
  '/servicos': typeof ServicosRoute
  '/sitemap-blog.xml': typeof SitemapBlogDotxmlRoute
  '/sitemap-cases.xml': typeof SitemapCasesDotxmlRoute
  '/sitemap-cities.xml': typeof SitemapCitiesDotxmlRoute
  '/sitemap-city-services.xml': typeof SitemapCityServicesDotxmlRoute
  '/sitemap-editorial.xml': typeof SitemapEditorialDotxmlRoute
  '/sitemap-marketplace.xml': typeof SitemapMarketplaceDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-services.xml': typeof SitemapServicesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/solicitar-orcamento': typeof SolicitarOrcamentoRoute
  '/termos': typeof TermosRoute
  '/trafego-pago': typeof TrafegoPagoRoute
  '/$city/$service': typeof CityServiceRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/automacao': typeof BlogAutomacaoRoute
  '/blog/conversao': typeof BlogConversaoRoute
  '/blog/google-meu-negocio': typeof BlogGoogleMeuNegocioRoute
  '/blog/ia': typeof BlogIaRoute
  '/blog/landing-pages': typeof BlogLandingPagesRoute
  '/blog/mapa': typeof BlogMapaRoute
  '/blog/marketing-local': typeof BlogMarketingLocalRoute
  '/blog/seo': typeof BlogSeoRoute
  '/blog/sites': typeof BlogSitesRoute
  '/blog/trafego-pago': typeof BlogTrafegoPagoRoute
  '/blog/vendas': typeof BlogVendasRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/cidade/$slug': typeof CidadeSlugRoute
  '/empresa/$slug': typeof EmpresaSlugRoute
  '/estados/$state': typeof EstadosStateRoute
  '/profissional/$slug': typeof ProfissionalSlugRoute
  '/r/$code': typeof RCodeRoute
  '/blog/': typeof BlogIndexRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/app/documents': typeof AuthenticatedAppDocumentsRoute
  '/app/editorial': typeof AuthenticatedAppEditorialRoute
  '/app/marketplace': typeof AuthenticatedAppMarketplaceRouteWithChildren
  '/app/master': typeof AuthenticatedAppMasterRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/parceiro': typeof AuthenticatedAppParceiroRoute
  '/app/portals': typeof AuthenticatedAppPortalsRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/projects': typeof AuthenticatedAppProjectsRouteWithChildren
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/support': typeof AuthenticatedAppSupportRouteWithChildren
  '/app/visitantes': typeof AuthenticatedAppVisitantesRoute
  '/api/public/lead-webhook': typeof ApiPublicLeadWebhookRoute
  '/blog/cluster/$cluster': typeof BlogClusterClusterRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/marketplace/admin': typeof AuthenticatedAppMarketplaceAdminRoute
  '/app/marketplace/company': typeof AuthenticatedAppMarketplaceCompanyRoute
  '/app/marketplace/provider': typeof AuthenticatedAppMarketplaceProviderRoute
  '/app/projects/$id': typeof AuthenticatedAppProjectsIdRoute
  '/app/support/$id': typeof AuthenticatedAppSupportIdRoute
  '/api/public/hooks/anomaly-scan': typeof ApiPublicHooksAnomalyScanRoute
  '/api/public/hooks/integration-healthcheck': typeof ApiPublicHooksIntegrationHealthcheckRoute
  '/api/public/hooks/lgpd-maintenance': typeof ApiPublicHooksLgpdMaintenanceRoute
  '/api/public/hooks/seo-monitor': typeof ApiPublicHooksSeoMonitorRoute
  '/api/public/hooks/visitors-cleanup': typeof ApiPublicHooksVisitorsCleanupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$service': typeof ServiceRoute
  '/auth': typeof AuthRoute
  '/automacao': typeof AutomacaoRoute
  '/cidades': typeof CidadesRoute
  '/consultoria': typeof ConsultoriaRoute
  '/contato': typeof ContatoRoute
  '/criacao-sites': typeof CriacaoSitesRoute
  '/desenvolvimento': typeof DesenvolvimentoRoute
  '/estados': typeof EstadosRouteWithChildren
  '/google-meu-negocio': typeof GoogleMeuNegocioRoute
  '/ia': typeof IaRoute
  '/marketplace': typeof MarketplaceRoute
  '/painel': typeof PainelRoute
  '/painel-crm': typeof PainelCrmRoute
  '/parceiros': typeof ParceirosRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/privacidade': typeof PrivacidadeRoute
  '/qa-events': typeof QaEventsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/seo': typeof SeoRoute
  '/servicos': typeof ServicosRoute
  '/sitemap-blog.xml': typeof SitemapBlogDotxmlRoute
  '/sitemap-cases.xml': typeof SitemapCasesDotxmlRoute
  '/sitemap-cities.xml': typeof SitemapCitiesDotxmlRoute
  '/sitemap-city-services.xml': typeof SitemapCityServicesDotxmlRoute
  '/sitemap-editorial.xml': typeof SitemapEditorialDotxmlRoute
  '/sitemap-marketplace.xml': typeof SitemapMarketplaceDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-services.xml': typeof SitemapServicesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/solicitar-orcamento': typeof SolicitarOrcamentoRoute
  '/termos': typeof TermosRoute
  '/trafego-pago': typeof TrafegoPagoRoute
  '/$city/$service': typeof CityServiceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/automacao': typeof BlogAutomacaoRoute
  '/blog/conversao': typeof BlogConversaoRoute
  '/blog/google-meu-negocio': typeof BlogGoogleMeuNegocioRoute
  '/blog/ia': typeof BlogIaRoute
  '/blog/landing-pages': typeof BlogLandingPagesRoute
  '/blog/mapa': typeof BlogMapaRoute
  '/blog/marketing-local': typeof BlogMarketingLocalRoute
  '/blog/seo': typeof BlogSeoRoute
  '/blog/sites': typeof BlogSitesRoute
  '/blog/trafego-pago': typeof BlogTrafegoPagoRoute
  '/blog/vendas': typeof BlogVendasRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/cidade/$slug': typeof CidadeSlugRoute
  '/empresa/$slug': typeof EmpresaSlugRoute
  '/estados/$state': typeof EstadosStateRoute
  '/profissional/$slug': typeof ProfissionalSlugRoute
  '/r/$code': typeof RCodeRoute
  '/blog': typeof BlogIndexRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/app/documents': typeof AuthenticatedAppDocumentsRoute
  '/app/editorial': typeof AuthenticatedAppEditorialRoute
  '/app/marketplace': typeof AuthenticatedAppMarketplaceRouteWithChildren
  '/app/master': typeof AuthenticatedAppMasterRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/parceiro': typeof AuthenticatedAppParceiroRoute
  '/app/portals': typeof AuthenticatedAppPortalsRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/projects': typeof AuthenticatedAppProjectsRouteWithChildren
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/support': typeof AuthenticatedAppSupportRouteWithChildren
  '/app/visitantes': typeof AuthenticatedAppVisitantesRoute
  '/api/public/lead-webhook': typeof ApiPublicLeadWebhookRoute
  '/blog/cluster/$cluster': typeof BlogClusterClusterRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/marketplace/admin': typeof AuthenticatedAppMarketplaceAdminRoute
  '/app/marketplace/company': typeof AuthenticatedAppMarketplaceCompanyRoute
  '/app/marketplace/provider': typeof AuthenticatedAppMarketplaceProviderRoute
  '/app/projects/$id': typeof AuthenticatedAppProjectsIdRoute
  '/app/support/$id': typeof AuthenticatedAppSupportIdRoute
  '/api/public/hooks/anomaly-scan': typeof ApiPublicHooksAnomalyScanRoute
  '/api/public/hooks/integration-healthcheck': typeof ApiPublicHooksIntegrationHealthcheckRoute
  '/api/public/hooks/lgpd-maintenance': typeof ApiPublicHooksLgpdMaintenanceRoute
  '/api/public/hooks/seo-monitor': typeof ApiPublicHooksSeoMonitorRoute
  '/api/public/hooks/visitors-cleanup': typeof ApiPublicHooksVisitorsCleanupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$service': typeof ServiceRoute
  '/auth': typeof AuthRoute
  '/automacao': typeof AutomacaoRoute
  '/cidades': typeof CidadesRoute
  '/consultoria': typeof ConsultoriaRoute
  '/contato': typeof ContatoRoute
  '/criacao-sites': typeof CriacaoSitesRoute
  '/desenvolvimento': typeof DesenvolvimentoRoute
  '/estados': typeof EstadosRouteWithChildren
  '/google-meu-negocio': typeof GoogleMeuNegocioRoute
  '/ia': typeof IaRoute
  '/marketplace': typeof MarketplaceRoute
  '/painel': typeof PainelRoute
  '/painel-crm': typeof PainelCrmRoute
  '/parceiros': typeof ParceirosRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/privacidade': typeof PrivacidadeRoute
  '/qa-events': typeof QaEventsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/seo': typeof SeoRoute
  '/servicos': typeof ServicosRoute
  '/sitemap-blog.xml': typeof SitemapBlogDotxmlRoute
  '/sitemap-cases.xml': typeof SitemapCasesDotxmlRoute
  '/sitemap-cities.xml': typeof SitemapCitiesDotxmlRoute
  '/sitemap-city-services.xml': typeof SitemapCityServicesDotxmlRoute
  '/sitemap-editorial.xml': typeof SitemapEditorialDotxmlRoute
  '/sitemap-marketplace.xml': typeof SitemapMarketplaceDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-services.xml': typeof SitemapServicesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/solicitar-orcamento': typeof SolicitarOrcamentoRoute
  '/termos': typeof TermosRoute
  '/trafego-pago': typeof TrafegoPagoRoute
  '/$city/$service': typeof CityServiceRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/automacao': typeof BlogAutomacaoRoute
  '/blog/conversao': typeof BlogConversaoRoute
  '/blog/google-meu-negocio': typeof BlogGoogleMeuNegocioRoute
  '/blog/ia': typeof BlogIaRoute
  '/blog/landing-pages': typeof BlogLandingPagesRoute
  '/blog/mapa': typeof BlogMapaRoute
  '/blog/marketing-local': typeof BlogMarketingLocalRoute
  '/blog/seo': typeof BlogSeoRoute
  '/blog/sites': typeof BlogSitesRoute
  '/blog/trafego-pago': typeof BlogTrafegoPagoRoute
  '/blog/vendas': typeof BlogVendasRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/cidade/$slug': typeof CidadeSlugRoute
  '/empresa/$slug': typeof EmpresaSlugRoute
  '/estados/$state': typeof EstadosStateRoute
  '/profissional/$slug': typeof ProfissionalSlugRoute
  '/r/$code': typeof RCodeRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRoute
  '/_authenticated/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/_authenticated/app/documents': typeof AuthenticatedAppDocumentsRoute
  '/_authenticated/app/editorial': typeof AuthenticatedAppEditorialRoute
  '/_authenticated/app/marketplace': typeof AuthenticatedAppMarketplaceRouteWithChildren
  '/_authenticated/app/master': typeof AuthenticatedAppMasterRoute
  '/_authenticated/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/app/parceiro': typeof AuthenticatedAppParceiroRoute
  '/_authenticated/app/portals': typeof AuthenticatedAppPortalsRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/projects': typeof AuthenticatedAppProjectsRouteWithChildren
  '/_authenticated/app/reports': typeof AuthenticatedAppReportsRoute
  '/_authenticated/app/support': typeof AuthenticatedAppSupportRouteWithChildren
  '/_authenticated/app/visitantes': typeof AuthenticatedAppVisitantesRoute
  '/api/public/lead-webhook': typeof ApiPublicLeadWebhookRoute
  '/blog/cluster/$cluster': typeof BlogClusterClusterRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/marketplace/admin': typeof AuthenticatedAppMarketplaceAdminRoute
  '/_authenticated/app/marketplace/company': typeof AuthenticatedAppMarketplaceCompanyRoute
  '/_authenticated/app/marketplace/provider': typeof AuthenticatedAppMarketplaceProviderRoute
  '/_authenticated/app/projects/$id': typeof AuthenticatedAppProjectsIdRoute
  '/_authenticated/app/support/$id': typeof AuthenticatedAppSupportIdRoute
  '/api/public/hooks/anomaly-scan': typeof ApiPublicHooksAnomalyScanRoute
  '/api/public/hooks/integration-healthcheck': typeof ApiPublicHooksIntegrationHealthcheckRoute
  '/api/public/hooks/lgpd-maintenance': typeof ApiPublicHooksLgpdMaintenanceRoute
  '/api/public/hooks/seo-monitor': typeof ApiPublicHooksSeoMonitorRoute
  '/api/public/hooks/visitors-cleanup': typeof ApiPublicHooksVisitorsCleanupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$service'
    | '/auth'
    | '/automacao'
    | '/cidades'
    | '/consultoria'
    | '/contato'
    | '/criacao-sites'
    | '/desenvolvimento'
    | '/estados'
    | '/google-meu-negocio'
    | '/ia'
    | '/marketplace'
    | '/painel'
    | '/painel-crm'
    | '/parceiros'
    | '/politica-privacidade'
    | '/privacidade'
    | '/qa-events'
    | '/reset-password'
    | '/rss.xml'
    | '/seo'
    | '/servicos'
    | '/sitemap-blog.xml'
    | '/sitemap-cases.xml'
    | '/sitemap-cities.xml'
    | '/sitemap-city-services.xml'
    | '/sitemap-editorial.xml'
    | '/sitemap-marketplace.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-services.xml'
    | '/sitemap.xml'
    | '/sobre'
    | '/solicitar-orcamento'
    | '/termos'
    | '/trafego-pago'
    | '/$city/$service'
    | '/app'
    | '/blog/$slug'
    | '/blog/automacao'
    | '/blog/conversao'
    | '/blog/google-meu-negocio'
    | '/blog/ia'
    | '/blog/landing-pages'
    | '/blog/mapa'
    | '/blog/marketing-local'
    | '/blog/seo'
    | '/blog/sites'
    | '/blog/trafego-pago'
    | '/blog/vendas'
    | '/cases/$slug'
    | '/categoria/$slug'
    | '/cidade/$slug'
    | '/empresa/$slug'
    | '/estados/$state'
    | '/profissional/$slug'
    | '/r/$code'
    | '/blog/'
    | '/app/admin'
    | '/app/campaigns'
    | '/app/documents'
    | '/app/editorial'
    | '/app/marketplace'
    | '/app/master'
    | '/app/notifications'
    | '/app/parceiro'
    | '/app/portals'
    | '/app/profile'
    | '/app/projects'
    | '/app/reports'
    | '/app/support'
    | '/app/visitantes'
    | '/api/public/lead-webhook'
    | '/blog/cluster/$cluster'
    | '/app/'
    | '/app/marketplace/admin'
    | '/app/marketplace/company'
    | '/app/marketplace/provider'
    | '/app/projects/$id'
    | '/app/support/$id'
    | '/api/public/hooks/anomaly-scan'
    | '/api/public/hooks/integration-healthcheck'
    | '/api/public/hooks/lgpd-maintenance'
    | '/api/public/hooks/seo-monitor'
    | '/api/public/hooks/visitors-cleanup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$service'
    | '/auth'
    | '/automacao'
    | '/cidades'
    | '/consultoria'
    | '/contato'
    | '/criacao-sites'
    | '/desenvolvimento'
    | '/estados'
    | '/google-meu-negocio'
    | '/ia'
    | '/marketplace'
    | '/painel'
    | '/painel-crm'
    | '/parceiros'
    | '/politica-privacidade'
    | '/privacidade'
    | '/qa-events'
    | '/reset-password'
    | '/rss.xml'
    | '/seo'
    | '/servicos'
    | '/sitemap-blog.xml'
    | '/sitemap-cases.xml'
    | '/sitemap-cities.xml'
    | '/sitemap-city-services.xml'
    | '/sitemap-editorial.xml'
    | '/sitemap-marketplace.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-services.xml'
    | '/sitemap.xml'
    | '/sobre'
    | '/solicitar-orcamento'
    | '/termos'
    | '/trafego-pago'
    | '/$city/$service'
    | '/blog/$slug'
    | '/blog/automacao'
    | '/blog/conversao'
    | '/blog/google-meu-negocio'
    | '/blog/ia'
    | '/blog/landing-pages'
    | '/blog/mapa'
    | '/blog/marketing-local'
    | '/blog/seo'
    | '/blog/sites'
    | '/blog/trafego-pago'
    | '/blog/vendas'
    | '/cases/$slug'
    | '/categoria/$slug'
    | '/cidade/$slug'
    | '/empresa/$slug'
    | '/estados/$state'
    | '/profissional/$slug'
    | '/r/$code'
    | '/blog'
    | '/app/admin'
    | '/app/campaigns'
    | '/app/documents'
    | '/app/editorial'
    | '/app/marketplace'
    | '/app/master'
    | '/app/notifications'
    | '/app/parceiro'
    | '/app/portals'
    | '/app/profile'
    | '/app/projects'
    | '/app/reports'
    | '/app/support'
    | '/app/visitantes'
    | '/api/public/lead-webhook'
    | '/blog/cluster/$cluster'
    | '/app'
    | '/app/marketplace/admin'
    | '/app/marketplace/company'
    | '/app/marketplace/provider'
    | '/app/projects/$id'
    | '/app/support/$id'
    | '/api/public/hooks/anomaly-scan'
    | '/api/public/hooks/integration-healthcheck'
    | '/api/public/hooks/lgpd-maintenance'
    | '/api/public/hooks/seo-monitor'
    | '/api/public/hooks/visitors-cleanup'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$service'
    | '/auth'
    | '/automacao'
    | '/cidades'
    | '/consultoria'
    | '/contato'
    | '/criacao-sites'
    | '/desenvolvimento'
    | '/estados'
    | '/google-meu-negocio'
    | '/ia'
    | '/marketplace'
    | '/painel'
    | '/painel-crm'
    | '/parceiros'
    | '/politica-privacidade'
    | '/privacidade'
    | '/qa-events'
    | '/reset-password'
    | '/rss.xml'
    | '/seo'
    | '/servicos'
    | '/sitemap-blog.xml'
    | '/sitemap-cases.xml'
    | '/sitemap-cities.xml'
    | '/sitemap-city-services.xml'
    | '/sitemap-editorial.xml'
    | '/sitemap-marketplace.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-services.xml'
    | '/sitemap.xml'
    | '/sobre'
    | '/solicitar-orcamento'
    | '/termos'
    | '/trafego-pago'
    | '/$city/$service'
    | '/_authenticated/app'
    | '/blog/$slug'
    | '/blog/automacao'
    | '/blog/conversao'
    | '/blog/google-meu-negocio'
    | '/blog/ia'
    | '/blog/landing-pages'
    | '/blog/mapa'
    | '/blog/marketing-local'
    | '/blog/seo'
    | '/blog/sites'
    | '/blog/trafego-pago'
    | '/blog/vendas'
    | '/cases/$slug'
    | '/categoria/$slug'
    | '/cidade/$slug'
    | '/empresa/$slug'
    | '/estados/$state'
    | '/profissional/$slug'
    | '/r/$code'
    | '/blog/'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/campaigns'
    | '/_authenticated/app/documents'
    | '/_authenticated/app/editorial'
    | '/_authenticated/app/marketplace'
    | '/_authenticated/app/master'
    | '/_authenticated/app/notifications'
    | '/_authenticated/app/parceiro'
    | '/_authenticated/app/portals'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/projects'
    | '/_authenticated/app/reports'
    | '/_authenticated/app/support'
    | '/_authenticated/app/visitantes'
    | '/api/public/lead-webhook'
    | '/blog/cluster/$cluster'
    | '/_authenticated/app/'
    | '/_authenticated/app/marketplace/admin'
    | '/_authenticated/app/marketplace/company'
    | '/_authenticated/app/marketplace/provider'
    | '/_authenticated/app/projects/$id'
    | '/_authenticated/app/support/$id'
    | '/api/public/hooks/anomaly-scan'
    | '/api/public/hooks/integration-healthcheck'
    | '/api/public/hooks/lgpd-maintenance'
    | '/api/public/hooks/seo-monitor'
    | '/api/public/hooks/visitors-cleanup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ServiceRoute: typeof ServiceRoute
  AuthRoute: typeof AuthRoute
  AutomacaoRoute: typeof AutomacaoRoute
  CidadesRoute: typeof CidadesRoute
  ConsultoriaRoute: typeof ConsultoriaRoute
  ContatoRoute: typeof ContatoRoute
  CriacaoSitesRoute: typeof CriacaoSitesRoute
  DesenvolvimentoRoute: typeof DesenvolvimentoRoute
  EstadosRoute: typeof EstadosRouteWithChildren
  GoogleMeuNegocioRoute: typeof GoogleMeuNegocioRoute
  IaRoute: typeof IaRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PainelRoute: typeof PainelRoute
  PainelCrmRoute: typeof PainelCrmRoute
  ParceirosRoute: typeof ParceirosRoute
  PoliticaPrivacidadeRoute: typeof PoliticaPrivacidadeRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  QaEventsRoute: typeof QaEventsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SeoRoute: typeof SeoRoute
  ServicosRoute: typeof ServicosRoute
  SitemapBlogDotxmlRoute: typeof SitemapBlogDotxmlRoute
  SitemapCasesDotxmlRoute: typeof SitemapCasesDotxmlRoute
  SitemapCitiesDotxmlRoute: typeof SitemapCitiesDotxmlRoute
  SitemapCityServicesDotxmlRoute: typeof SitemapCityServicesDotxmlRoute
  SitemapEditorialDotxmlRoute: typeof SitemapEditorialDotxmlRoute
  SitemapMarketplaceDotxmlRoute: typeof SitemapMarketplaceDotxmlRoute
  SitemapPagesDotxmlRoute: typeof SitemapPagesDotxmlRoute
  SitemapServicesDotxmlRoute: typeof SitemapServicesDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  SolicitarOrcamentoRoute: typeof SolicitarOrcamentoRoute
  TermosRoute: typeof TermosRoute
  TrafegoPagoRoute: typeof TrafegoPagoRoute
  CityServiceRoute: typeof CityServiceRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogAutomacaoRoute: typeof BlogAutomacaoRoute
  BlogConversaoRoute: typeof BlogConversaoRoute
  BlogGoogleMeuNegocioRoute: typeof BlogGoogleMeuNegocioRoute
  BlogIaRoute: typeof BlogIaRoute
  BlogLandingPagesRoute: typeof BlogLandingPagesRoute
  BlogMapaRoute: typeof BlogMapaRoute
  BlogMarketingLocalRoute: typeof BlogMarketingLocalRoute
  BlogSeoRoute: typeof BlogSeoRoute
  BlogSitesRoute: typeof BlogSitesRoute
  BlogTrafegoPagoRoute: typeof BlogTrafegoPagoRoute
  BlogVendasRoute: typeof BlogVendasRoute
  CasesSlugRoute: typeof CasesSlugRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  CidadeSlugRoute: typeof CidadeSlugRoute
  EmpresaSlugRoute: typeof EmpresaSlugRoute
  ProfissionalSlugRoute: typeof ProfissionalSlugRoute
  RCodeRoute: typeof RCodeRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicLeadWebhookRoute: typeof ApiPublicLeadWebhookRoute
  BlogClusterClusterRoute: typeof BlogClusterClusterRoute
  ApiPublicHooksAnomalyScanRoute: typeof ApiPublicHooksAnomalyScanRoute
  ApiPublicHooksIntegrationHealthcheckRoute: typeof ApiPublicHooksIntegrationHealthcheckRoute
  ApiPublicHooksLgpdMaintenanceRoute: typeof ApiPublicHooksLgpdMaintenanceRoute
  ApiPublicHooksSeoMonitorRoute: typeof ApiPublicHooksSeoMonitorRoute
  ApiPublicHooksVisitorsCleanupRoute: typeof ApiPublicHooksVisitorsCleanupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trafego-pago': {
      id: '/trafego-pago'
      path: '/trafego-pago'
      fullPath: '/trafego-pago'
      preLoaderRoute: typeof TrafegoPagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitar-orcamento': {
      id: '/solicitar-orcamento'
      path: '/solicitar-orcamento'
      fullPath: '/solicitar-orcamento'
      preLoaderRoute: typeof SolicitarOrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-services.xml': {
      id: '/sitemap-services.xml'
      path: '/sitemap-services.xml'
      fullPath: '/sitemap-services.xml'
      preLoaderRoute: typeof SitemapServicesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pages.xml': {
      id: '/sitemap-pages.xml'
      path: '/sitemap-pages.xml'
      fullPath: '/sitemap-pages.xml'
      preLoaderRoute: typeof SitemapPagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-marketplace.xml': {
      id: '/sitemap-marketplace.xml'
      path: '/sitemap-marketplace.xml'
      fullPath: '/sitemap-marketplace.xml'
      preLoaderRoute: typeof SitemapMarketplaceDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-editorial.xml': {
      id: '/sitemap-editorial.xml'
      path: '/sitemap-editorial.xml'
      fullPath: '/sitemap-editorial.xml'
      preLoaderRoute: typeof SitemapEditorialDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-city-services.xml': {
      id: '/sitemap-city-services.xml'
      path: '/sitemap-city-services.xml'
      fullPath: '/sitemap-city-services.xml'
      preLoaderRoute: typeof SitemapCityServicesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-cities.xml': {
      id: '/sitemap-cities.xml'
      path: '/sitemap-cities.xml'
      fullPath: '/sitemap-cities.xml'
      preLoaderRoute: typeof SitemapCitiesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-cases.xml': {
      id: '/sitemap-cases.xml'
      path: '/sitemap-cases.xml'
      fullPath: '/sitemap-cases.xml'
      preLoaderRoute: typeof SitemapCasesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-blog.xml': {
      id: '/sitemap-blog.xml'
      path: '/sitemap-blog.xml'
      fullPath: '/sitemap-blog.xml'
      preLoaderRoute: typeof SitemapBlogDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo': {
      id: '/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof SeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-events': {
      id: '/qa-events'
      path: '/qa-events'
      fullPath: '/qa-events'
      preLoaderRoute: typeof QaEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-privacidade': {
      id: '/politica-privacidade'
      path: '/politica-privacidade'
      fullPath: '/politica-privacidade'
      preLoaderRoute: typeof PoliticaPrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros': {
      id: '/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof ParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-crm': {
      id: '/painel-crm'
      path: '/painel-crm'
      fullPath: '/painel-crm'
      preLoaderRoute: typeof PainelCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-meu-negocio': {
      id: '/google-meu-negocio'
      path: '/google-meu-negocio'
      fullPath: '/google-meu-negocio'
      preLoaderRoute: typeof GoogleMeuNegocioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estados': {
      id: '/estados'
      path: '/estados'
      fullPath: '/estados'
      preLoaderRoute: typeof EstadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desenvolvimento': {
      id: '/desenvolvimento'
      path: '/desenvolvimento'
      fullPath: '/desenvolvimento'
      preLoaderRoute: typeof DesenvolvimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criacao-sites': {
      id: '/criacao-sites'
      path: '/criacao-sites'
      fullPath: '/criacao-sites'
      preLoaderRoute: typeof CriacaoSitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultoria': {
      id: '/consultoria'
      path: '/consultoria'
      fullPath: '/consultoria'
      preLoaderRoute: typeof ConsultoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cidades': {
      id: '/cidades'
      path: '/cidades'
      fullPath: '/cidades'
      preLoaderRoute: typeof CidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacao': {
      id: '/automacao'
      path: '/automacao'
      fullPath: '/automacao'
      preLoaderRoute: typeof AutomacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$service': {
      id: '/$service'
      path: '/$service'
      fullPath: '/$service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissional/$slug': {
      id: '/profissional/$slug'
      path: '/profissional/$slug'
      fullPath: '/profissional/$slug'
      preLoaderRoute: typeof ProfissionalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estados/$state': {
      id: '/estados/$state'
      path: '/$state'
      fullPath: '/estados/$state'
      preLoaderRoute: typeof EstadosStateRouteImport
      parentRoute: typeof EstadosRoute
    }
    '/empresa/$slug': {
      id: '/empresa/$slug'
      path: '/empresa/$slug'
      fullPath: '/empresa/$slug'
      preLoaderRoute: typeof EmpresaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cidade/$slug': {
      id: '/cidade/$slug'
      path: '/cidade/$slug'
      fullPath: '/cidade/$slug'
      preLoaderRoute: typeof CidadeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$slug': {
      id: '/cases/$slug'
      path: '/cases/$slug'
      fullPath: '/cases/$slug'
      preLoaderRoute: typeof CasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/vendas': {
      id: '/blog/vendas'
      path: '/blog/vendas'
      fullPath: '/blog/vendas'
      preLoaderRoute: typeof BlogVendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/trafego-pago': {
      id: '/blog/trafego-pago'
      path: '/blog/trafego-pago'
      fullPath: '/blog/trafego-pago'
      preLoaderRoute: typeof BlogTrafegoPagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/sites': {
      id: '/blog/sites'
      path: '/blog/sites'
      fullPath: '/blog/sites'
      preLoaderRoute: typeof BlogSitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/seo': {
      id: '/blog/seo'
      path: '/blog/seo'
      fullPath: '/blog/seo'
      preLoaderRoute: typeof BlogSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/marketing-local': {
      id: '/blog/marketing-local'
      path: '/blog/marketing-local'
      fullPath: '/blog/marketing-local'
      preLoaderRoute: typeof BlogMarketingLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/mapa': {
      id: '/blog/mapa'
      path: '/blog/mapa'
      fullPath: '/blog/mapa'
      preLoaderRoute: typeof BlogMapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/landing-pages': {
      id: '/blog/landing-pages'
      path: '/blog/landing-pages'
      fullPath: '/blog/landing-pages'
      preLoaderRoute: typeof BlogLandingPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/ia': {
      id: '/blog/ia'
      path: '/blog/ia'
      fullPath: '/blog/ia'
      preLoaderRoute: typeof BlogIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/google-meu-negocio': {
      id: '/blog/google-meu-negocio'
      path: '/blog/google-meu-negocio'
      fullPath: '/blog/google-meu-negocio'
      preLoaderRoute: typeof BlogGoogleMeuNegocioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/conversao': {
      id: '/blog/conversao'
      path: '/blog/conversao'
      fullPath: '/blog/conversao'
      preLoaderRoute: typeof BlogConversaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/automacao': {
      id: '/blog/automacao'
      path: '/blog/automacao'
      fullPath: '/blog/automacao'
      preLoaderRoute: typeof BlogAutomacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/$city/$service': {
      id: '/$city/$service'
      path: '/$city/$service'
      fullPath: '/$city/$service'
      preLoaderRoute: typeof CityServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/blog/cluster/$cluster': {
      id: '/blog/cluster/$cluster'
      path: '/blog/cluster/$cluster'
      fullPath: '/blog/cluster/$cluster'
      preLoaderRoute: typeof BlogClusterClusterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead-webhook': {
      id: '/api/public/lead-webhook'
      path: '/api/public/lead-webhook'
      fullPath: '/api/public/lead-webhook'
      preLoaderRoute: typeof ApiPublicLeadWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/visitantes': {
      id: '/_authenticated/app/visitantes'
      path: '/visitantes'
      fullPath: '/app/visitantes'
      preLoaderRoute: typeof AuthenticatedAppVisitantesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/support': {
      id: '/_authenticated/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AuthenticatedAppSupportRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/reports': {
      id: '/_authenticated/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AuthenticatedAppReportsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/projects': {
      id: '/_authenticated/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AuthenticatedAppProjectsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/portals': {
      id: '/_authenticated/app/portals'
      path: '/portals'
      fullPath: '/app/portals'
      preLoaderRoute: typeof AuthenticatedAppPortalsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/parceiro': {
      id: '/_authenticated/app/parceiro'
      path: '/parceiro'
      fullPath: '/app/parceiro'
      preLoaderRoute: typeof AuthenticatedAppParceiroRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notifications': {
      id: '/_authenticated/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/master': {
      id: '/_authenticated/app/master'
      path: '/master'
      fullPath: '/app/master'
      preLoaderRoute: typeof AuthenticatedAppMasterRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/marketplace': {
      id: '/_authenticated/app/marketplace'
      path: '/marketplace'
      fullPath: '/app/marketplace'
      preLoaderRoute: typeof AuthenticatedAppMarketplaceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/editorial': {
      id: '/_authenticated/app/editorial'
      path: '/editorial'
      fullPath: '/app/editorial'
      preLoaderRoute: typeof AuthenticatedAppEditorialRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/documents': {
      id: '/_authenticated/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AuthenticatedAppDocumentsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/campaigns': {
      id: '/_authenticated/app/campaigns'
      path: '/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AuthenticatedAppCampaignsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/hooks/visitors-cleanup': {
      id: '/api/public/hooks/visitors-cleanup'
      path: '/api/public/hooks/visitors-cleanup'
      fullPath: '/api/public/hooks/visitors-cleanup'
      preLoaderRoute: typeof ApiPublicHooksVisitorsCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/seo-monitor': {
      id: '/api/public/hooks/seo-monitor'
      path: '/api/public/hooks/seo-monitor'
      fullPath: '/api/public/hooks/seo-monitor'
      preLoaderRoute: typeof ApiPublicHooksSeoMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/lgpd-maintenance': {
      id: '/api/public/hooks/lgpd-maintenance'
      path: '/api/public/hooks/lgpd-maintenance'
      fullPath: '/api/public/hooks/lgpd-maintenance'
      preLoaderRoute: typeof ApiPublicHooksLgpdMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/integration-healthcheck': {
      id: '/api/public/hooks/integration-healthcheck'
      path: '/api/public/hooks/integration-healthcheck'
      fullPath: '/api/public/hooks/integration-healthcheck'
      preLoaderRoute: typeof ApiPublicHooksIntegrationHealthcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/anomaly-scan': {
      id: '/api/public/hooks/anomaly-scan'
      path: '/api/public/hooks/anomaly-scan'
      fullPath: '/api/public/hooks/anomaly-scan'
      preLoaderRoute: typeof ApiPublicHooksAnomalyScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/support/$id': {
      id: '/_authenticated/app/support/$id'
      path: '/$id'
      fullPath: '/app/support/$id'
      preLoaderRoute: typeof AuthenticatedAppSupportIdRouteImport
      parentRoute: typeof AuthenticatedAppSupportRoute
    }
    '/_authenticated/app/projects/$id': {
      id: '/_authenticated/app/projects/$id'
      path: '/$id'
      fullPath: '/app/projects/$id'
      preLoaderRoute: typeof AuthenticatedAppProjectsIdRouteImport
      parentRoute: typeof AuthenticatedAppProjectsRoute
    }
    '/_authenticated/app/marketplace/provider': {
      id: '/_authenticated/app/marketplace/provider'
      path: '/provider'
      fullPath: '/app/marketplace/provider'
      preLoaderRoute: typeof AuthenticatedAppMarketplaceProviderRouteImport
      parentRoute: typeof AuthenticatedAppMarketplaceRoute
    }
    '/_authenticated/app/marketplace/company': {
      id: '/_authenticated/app/marketplace/company'
      path: '/company'
      fullPath: '/app/marketplace/company'
      preLoaderRoute: typeof AuthenticatedAppMarketplaceCompanyRouteImport
      parentRoute: typeof AuthenticatedAppMarketplaceRoute
    }
    '/_authenticated/app/marketplace/admin': {
      id: '/_authenticated/app/marketplace/admin'
      path: '/admin'
      fullPath: '/app/marketplace/admin'
      preLoaderRoute: typeof AuthenticatedAppMarketplaceAdminRouteImport
      parentRoute: typeof AuthenticatedAppMarketplaceRoute
    }
  }
}

interface AuthenticatedAppMarketplaceRouteChildren {
  AuthenticatedAppMarketplaceAdminRoute: typeof AuthenticatedAppMarketplaceAdminRoute
  AuthenticatedAppMarketplaceCompanyRoute: typeof AuthenticatedAppMarketplaceCompanyRoute
  AuthenticatedAppMarketplaceProviderRoute: typeof AuthenticatedAppMarketplaceProviderRoute
}

const AuthenticatedAppMarketplaceRouteChildren: AuthenticatedAppMarketplaceRouteChildren =
  {
    AuthenticatedAppMarketplaceAdminRoute:
      AuthenticatedAppMarketplaceAdminRoute,
    AuthenticatedAppMarketplaceCompanyRoute:
      AuthenticatedAppMarketplaceCompanyRoute,
    AuthenticatedAppMarketplaceProviderRoute:
      AuthenticatedAppMarketplaceProviderRoute,
  }

const AuthenticatedAppMarketplaceRouteWithChildren =
  AuthenticatedAppMarketplaceRoute._addFileChildren(
    AuthenticatedAppMarketplaceRouteChildren,
  )

interface AuthenticatedAppProjectsRouteChildren {
  AuthenticatedAppProjectsIdRoute: typeof AuthenticatedAppProjectsIdRoute
}

const AuthenticatedAppProjectsRouteChildren: AuthenticatedAppProjectsRouteChildren =
  {
    AuthenticatedAppProjectsIdRoute: AuthenticatedAppProjectsIdRoute,
  }

const AuthenticatedAppProjectsRouteWithChildren =
  AuthenticatedAppProjectsRoute._addFileChildren(
    AuthenticatedAppProjectsRouteChildren,
  )

interface AuthenticatedAppSupportRouteChildren {
  AuthenticatedAppSupportIdRoute: typeof AuthenticatedAppSupportIdRoute
}

const AuthenticatedAppSupportRouteChildren: AuthenticatedAppSupportRouteChildren =
  {
    AuthenticatedAppSupportIdRoute: AuthenticatedAppSupportIdRoute,
  }

const AuthenticatedAppSupportRouteWithChildren =
  AuthenticatedAppSupportRoute._addFileChildren(
    AuthenticatedAppSupportRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRoute
  AuthenticatedAppCampaignsRoute: typeof AuthenticatedAppCampaignsRoute
  AuthenticatedAppDocumentsRoute: typeof AuthenticatedAppDocumentsRoute
  AuthenticatedAppEditorialRoute: typeof AuthenticatedAppEditorialRoute
  AuthenticatedAppMarketplaceRoute: typeof AuthenticatedAppMarketplaceRouteWithChildren
  AuthenticatedAppMasterRoute: typeof AuthenticatedAppMasterRoute
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppParceiroRoute: typeof AuthenticatedAppParceiroRoute
  AuthenticatedAppPortalsRoute: typeof AuthenticatedAppPortalsRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppProjectsRoute: typeof AuthenticatedAppProjectsRouteWithChildren
  AuthenticatedAppReportsRoute: typeof AuthenticatedAppReportsRoute
  AuthenticatedAppSupportRoute: typeof AuthenticatedAppSupportRouteWithChildren
  AuthenticatedAppVisitantesRoute: typeof AuthenticatedAppVisitantesRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRoute,
  AuthenticatedAppCampaignsRoute: AuthenticatedAppCampaignsRoute,
  AuthenticatedAppDocumentsRoute: AuthenticatedAppDocumentsRoute,
  AuthenticatedAppEditorialRoute: AuthenticatedAppEditorialRoute,
  AuthenticatedAppMarketplaceRoute:
    AuthenticatedAppMarketplaceRouteWithChildren,
  AuthenticatedAppMasterRoute: AuthenticatedAppMasterRoute,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppParceiroRoute: AuthenticatedAppParceiroRoute,
  AuthenticatedAppPortalsRoute: AuthenticatedAppPortalsRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppProjectsRoute: AuthenticatedAppProjectsRouteWithChildren,
  AuthenticatedAppReportsRoute: AuthenticatedAppReportsRoute,
  AuthenticatedAppSupportRoute: AuthenticatedAppSupportRouteWithChildren,
  AuthenticatedAppVisitantesRoute: AuthenticatedAppVisitantesRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface EstadosRouteChildren {
  EstadosStateRoute: typeof EstadosStateRoute
}

const EstadosRouteChildren: EstadosRouteChildren = {
  EstadosStateRoute: EstadosStateRoute,
}

const EstadosRouteWithChildren =
  EstadosRoute._addFileChildren(EstadosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ServiceRoute: ServiceRoute,
  AuthRoute: AuthRoute,
  AutomacaoRoute: AutomacaoRoute,
  CidadesRoute: CidadesRoute,
  ConsultoriaRoute: ConsultoriaRoute,
  ContatoRoute: ContatoRoute,
  CriacaoSitesRoute: CriacaoSitesRoute,
  DesenvolvimentoRoute: DesenvolvimentoRoute,
  EstadosRoute: EstadosRouteWithChildren,
  GoogleMeuNegocioRoute: GoogleMeuNegocioRoute,
  IaRoute: IaRoute,
  MarketplaceRoute: MarketplaceRoute,
  PainelRoute: PainelRoute,
  PainelCrmRoute: PainelCrmRoute,
  ParceirosRoute: ParceirosRoute,
  PoliticaPrivacidadeRoute: PoliticaPrivacidadeRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  QaEventsRoute: QaEventsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SeoRoute: SeoRoute,
  ServicosRoute: ServicosRoute,
  SitemapBlogDotxmlRoute: SitemapBlogDotxmlRoute,
  SitemapCasesDotxmlRoute: SitemapCasesDotxmlRoute,
  SitemapCitiesDotxmlRoute: SitemapCitiesDotxmlRoute,
  SitemapCityServicesDotxmlRoute: SitemapCityServicesDotxmlRoute,
  SitemapEditorialDotxmlRoute: SitemapEditorialDotxmlRoute,
  SitemapMarketplaceDotxmlRoute: SitemapMarketplaceDotxmlRoute,
  SitemapPagesDotxmlRoute: SitemapPagesDotxmlRoute,
  SitemapServicesDotxmlRoute: SitemapServicesDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  SolicitarOrcamentoRoute: SolicitarOrcamentoRoute,
  TermosRoute: TermosRoute,
  TrafegoPagoRoute: TrafegoPagoRoute,
  CityServiceRoute: CityServiceRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogAutomacaoRoute: BlogAutomacaoRoute,
  BlogConversaoRoute: BlogConversaoRoute,
  BlogGoogleMeuNegocioRoute: BlogGoogleMeuNegocioRoute,
  BlogIaRoute: BlogIaRoute,
  BlogLandingPagesRoute: BlogLandingPagesRoute,
  BlogMapaRoute: BlogMapaRoute,
  BlogMarketingLocalRoute: BlogMarketingLocalRoute,
  BlogSeoRoute: BlogSeoRoute,
  BlogSitesRoute: BlogSitesRoute,
  BlogTrafegoPagoRoute: BlogTrafegoPagoRoute,
  BlogVendasRoute: BlogVendasRoute,
  CasesSlugRoute: CasesSlugRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  CidadeSlugRoute: CidadeSlugRoute,
  EmpresaSlugRoute: EmpresaSlugRoute,
  ProfissionalSlugRoute: ProfissionalSlugRoute,
  RCodeRoute: RCodeRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicLeadWebhookRoute: ApiPublicLeadWebhookRoute,
  BlogClusterClusterRoute: BlogClusterClusterRoute,
  ApiPublicHooksAnomalyScanRoute: ApiPublicHooksAnomalyScanRoute,
  ApiPublicHooksIntegrationHealthcheckRoute:
    ApiPublicHooksIntegrationHealthcheckRoute,
  ApiPublicHooksLgpdMaintenanceRoute: ApiPublicHooksLgpdMaintenanceRoute,
  ApiPublicHooksSeoMonitorRoute: ApiPublicHooksSeoMonitorRoute,
  ApiPublicHooksVisitorsCleanupRoute: ApiPublicHooksVisitorsCleanupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
